version: '3'

services: 
  backend:
    build: ./
    container_name: nestjs_api
    environment:
      - PORT=80
      - JWT_SECRET=123
      - MONGO_URI=mongodb+srv://giadinhthai:Ngpro123@cluster0.gtocs.mongodb.net/365truck
    ports:
      - '80:80'
    depends_on:
      - database
    networks:
      - nestjs_network
  
  database:
    image: mongo
    container_name: mongo_db    
    ports:
      - '27017:27017'
    volumes:
      - './mongodb-backup:/data/db'
    networks:
      - nestjs_network

networks:
  nestjs_network:
    driver: bridge
